### ISSUE TITLE
Replace use of deprecated brian2 function get_unit_fast()

### ISSUE THREAD

**Issue by Felix11H** [SmokinCaterpillar/pypet#48]
The most recent release of brian2 does no longer provide `get_unit_fast() ` leading to an import error.

I have from `pip freeze`

```
Brian2==2.0.2.1
Jinja2==2.9.6
MarkupSafe==1.0
mpmath==1.0.0
numexpr==2.6.2
numpy==1.13.1
pandas==0.20.3
pkg-resources==0.0.0
py-cpuinfo==3.3.0
pyparsing==2.2.0
pypet==0.4.0
```

and from `pypet.brian2 import NetworkManager` gives 

```
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: /tmp/brian_debug_da1deeh2.log  Thanks! [brian2]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/hoffmann/env/pypet-test/lib/python3.5/site-packages/pypet/brian2/__init__.py", line 4, in <module>
    from pypet.brian2.parameter import Brian2Parameter, Brian2Result, Brian2MonitorResult
  File "/home/hoffmann/env/pypet-test/lib/python3.5/site-packages/pypet/brian2/parameter.py", line 19, in <module>
    from brian2.units.fundamentalunits import Quantity, get_unit_fast, have_same_dimensions
ImportError: cannot import name 'get_unit_fast'
```

**Comment by SmokinCaterpillar** [comment]
Hi, seems like they changed the API, I'll look into it.

**Comment by Felix11H** [comment]
Yes, it seems they have removed this particular function. It was implemented as 

```
def get_unit_fast(x):
    '''
    Return a `Quantity` with value 1 and the same dimensions.
    '''
    return Quantity.with_dimensions(1, get_dimensions(x))
```

See for example [here](http://brian2.readthedocs.io/en/2.0rc/_modules/brian2/units/fundamentalunits.html#get_unit_fast).

Off-topic: I'm quite stuck now with this [mailing list question](https://groups.google.com/forum/?hl=de#!topic/pypet/SM54UKdg0EY). Could you take a look? Thank you!

**Comment by SmokinCaterpillar** [comment]
should work in the new 0.4.1 now
